config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'
  resource :sessions, only: [:create, :destroy]
  resources :servers, only: [:index, :new, :create, :show, :edit, :update]
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :server

  before_save EncryptionWrapper.new('password')
  after_save EncryptionWrapper.new('password')
  after_find EncryptionWrapper.new('password')


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip_address.rb
class IpAddress < ApplicationRecord
  enum address_type: {external: 0, internal: 1}
  belongs_to :server
end

app/models/server.rb
class Server < ApplicationRecord
  paginates_per 10
  has_many :ip_addresses
  has_many :internal_ip_addresses, -> { where(address_type: :internal) }, class_name: "IpAddress"
  has_many :external_ip_addresses, -> { where(address_type: :external) }, class_name: "IpAddress"
  has_many :accounts
  
end

app/models/server_form.rb
class ServerForm
  include ActiveModel::Model
  
  attr_accessor :server, :accounts_data, :ip_addresses_data

  def server
    @server ||= Server.new
  end

  def ip_addresses_data
    @ip_addresses_data ||= []
  end

  def accounts_data
    @accounts_data ||= []
  end

  def self.server_attributes
    Server.column_names.push(Server.reflections.keys).flatten
  end

  def self.ip_address_attributes
    IpAddress.column_names.push(IpAddress.reflections.keys).flatten
  end

  def self.account_attributes
    Account.column_names.push(Account.reflections.keys).flatten
  end

  server_attributes.each do |attr|
    delegate attr.to_sym, "#{attr}=".to_sym, to: :server
  end

  delegate :id, :persisted?, to: :server

  def self.model_name
    new.server.model_name
  end


  def build_object(params)
    if server.persisted?
      destroy_associated_records
    end
    server_attributes = params[:server].slice(*self.class.server_attributes)
    server.assign_attributes(server_attributes)
    build_ip_addresses(params[:ip_addresses_data])
    build_accounts(params[:accounts_data])

    setup_association
  end

  def save
    if valid?
      server.save!
    end
  end

  private

  def setup_association
    server.accounts << accounts_data
    server.ip_addresses << ip_addresses_data
  end

  def destroy_associated_records
    server.ip_addresses.destroy_all
    server.accounts.destroy_all
  end

  def build_ip_addresses(ip_addresses_params)
    ip_addresses_params.each do |ip_address_params|
      ip_address_attributes = ip_address_params.slice(*self.class.ip_address_attributes)
      ip_addresses_data << IpAddress.new(ip_address_attributes)
    end
  end

  def build_accounts(accounts_params)
    accounts_params.each do |account_params|
      account_attributes = account_params.slice(*self.class.account_attributes)
      accounts_data << Account.new(account_attributes)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method = :current_user

  def authorize
    unless current_user
      flash[:error] = "Authentication is required !!"
      redirect_to root_path
    end
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  before_action :authorize

  def index
    @servers = Server.includes(:ip_addresses).page params[:page]
  end

  def new
    @server_form = ServerForm.new()
  end

  def create
    @server_form = ServerForm.new
    @server_form.build_object(server_form_params)

    if @server_form.save
      flash[:success] = "Server details created successfully"
      redirect_to servers_path
    else
      render :new
    end
  end

  def show
    @server = Server.find(params[:id])
  end

  def edit
    server = Server.find(params[:id])
    @server_form = ServerForm.new(server: server, accounts_data: server.accounts, ip_addresses_data: server.ip_addresses)
  end

  def update
    server = Server.find(params[:id])
    @server_form = ServerForm.new(server: server, accounts_data: server.accounts, ip_addresses_data: server.ip_addresses)
    @server_form.build_object(server_form_params)
    if @server_form.save
      flash[:success] = "Server details created successfully"
      redirect_to servers_path
    else
      render :new
    end
  end

  private

  def server_form_params
    params.permit(
      server: [:name, :cpu, :drive, :ram, :os, :os_type, :applications],
      ip_addresses_data: [:ip, :network_mask, :network_address, :gateway, :address_type],
      accounts_data: [:user, :password, :account_type]
    )
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def new
    
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      login_user(user)
    else
      flash.now[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to root_path
    
  end

  private

  def login_user(user)
    session[:user_id] = user.id
    flash[:success] = "Welcome, you are now logged in"
    redirect_to servers_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/helpers/server_helper.rb
module ServerHelper
  def display_by_line(array_items)
    simple_format(array_items.join("\n"))
  end
end

app/views/application/_flashes.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:error] %>
       var $toastContent = $('<span><%= flash[:error] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
 <nav class="light-blue">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Admin Friend</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Server List", servers_path %></li>
        <li><%= link_to "Log out", sessions_path, method: :delete%></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendAdmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/navigation" %>
    <%= render "flashes", flash: flash %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/servers/_account_fields.html.erb
<% @id = Time.now.to_i %>
<div class="row account-group">
  <div class="input-field col s2">
    <%= label_tag "account_type_#{@id}", "Account type" %>
    <%= text_field_tag "accounts_data[][account_type]", account.account_type, id: "account_type_#{@id}" %>
  </div>
  <div class="input-field col s2">
    <%= label_tag "user_#{@id}", "User" %>
    <%= text_field_tag "accounts_data[][user]", account.user, id: "user_#{@id}"%>
  </div>
  <div class="input-field col s2">
    <%= label_tag "password_#{@id}", "Password" %>
    <%= text_field_tag "accounts_data[][password]", account.password, id: "password_#{@id}" %>
  </div>

  <div class="input-field col s2">
    <a href="#" class="remove-account"><i class="material-icons">clear</i></a>
  </div>
</div>

app/views/servers/_form.html.erb
<%= form_for @server_form do |f| %>
  <div class="row">
    <div class="section">
      <div class="input-field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field">
        <%= f.label :cpu, "CPU" %>
        <%= f.text_field :cpu %>
      </div>
      <div class="input-field">
        <%= f.label :ram, "RAM" %>
        <%= f.text_field :ram %>
      </div>
      <div class="input-field">
        <%= f.label :drive %>
        <%= f.text_field :drive %>
      </div>
      <div class="input-field">
        <%= f.label :os, "OS" %>
        <%= f.text_field :os %>
      </div>
      <div class="input-field">
        <%= f.label :os_type, "OS Type" %>
        <%= f.text_field :os_type %>
      </div>
      <div class="input-field">
        <%= f.label :applications, "Installed Applications" %>
        <%= f.text_area :applications, cols: 20, rows: 40, class: 'materialize-textarea' %>
      </div>
    </div>

    <hr>
    <h5 class="center-align">IP Addresses</h5>
    <hr>

    <div id="ip-addresses" class="section">
      <% if @server_form.ip_addresses_data.blank? %>
        <%= render partial: 'ip_address_fields', locals: {ip_address: IpAddress.new} %>
      <% else %>
        <% @server_form.ip_addresses_data.each do |ip_address| %>
          <%= render partial: 'ip_address_fields', locals: {ip_address: ip_address } %>
        <% end %>
      <% end %>
    </div>

    <a href="javascript:;" id="addIpAddress" class="valign-wrapper">
        <i class="material-icons">add_circle</i> Add IP Address
    </a>

    <hr>
    <h5 class="center-align">Accounts</h5>
    <hr>

    <div id="accounts" class="section">
      <% if @server_form.accounts_data.blank? %>
        <%= render partial: 'account_fields', locals: {account: Account.new} %>
      <% else %>
        <% @server_form.accounts_data.each do |account| %>
          <%= render partial: 'account_fields', locals: {account: account} %>
        <% end %>
      <% end %>
    </div>
    <a href="javascript:;" id="addAccount" class="valign-wrapper">
      <i class="material-icons">add_circle</i> Add Account
    </a> 
    <br>
    <div class="valign-wrapper">
      <%= f.submit class: "waves-effect waves-light btn" %> <span>or <%= link_to "Cancel", servers_path %></span>
    </div>
  </div>
<% end %>

<div style="display: none;" id="new-ip-address-form">
  <%= render partial: 'ip_address_fields', locals: {ip_address: IpAddress.new} %>
</div>

<div style="display: none;" id="new-account-form">
  <%= render partial: 'account_fields', locals: {account: Account.new} %>
</div>

app/views/servers/_ip_address_fields.html.erb
<div class="row ip-address-group">
  <div class="input-field col s2">
    <%= label_tag :ip, "IP address" %>
    <%= text_field_tag "ip_addresses_data[][ip]", ip_address.ip, id: 'ip' %>
  </div>
  <div class="input-field col s2">
    <%= label_tag :network_mask %>
    <%= text_field_tag "ip_addresses_data[][network_mask]", ip_address.network_mask, id: 'network_mask' %>
  </div>
  <div class="input-field col s2">
    <%= label_tag :network_address %>
    <%= text_field_tag "ip_addresses_data[][network_address]", ip_address.network_address, id: 'network_address' %>
  </div>
  <div class="input-field col s2">
    <%= label_tag :gateway %>
    <%= text_field_tag "ip_addresses_data[][gateway]", ip_address.gateway, id: 'gateway' %>
  </div>
  <div class="input-field col s2">
    <%= select_tag("ip_addresses_data[][address_type]", options_for_select(IpAddress.address_types.keys, ip_address.address_type), prompt: 'Address Type', class: 'browser-default') %>
  </div>
  <div class="input-field col s2">
    <a href="#" class="remove-ip-address"><i class="material-icons">clear</i></a>
  </div>

</div>

app/views/servers/edit.html.erb
<%= render 'form' %>

app/views/servers/index.html.erb
<h3 class="center-align">Servers</h3>
<table class="bordered centered">
  <thead>
    <tr>
      <th>Name</th>
      <th>OS</th>
      <th>OS Type</th>
      <th>Internal IP</th>
      <th>External IP</th>
    </tr>
  </thead>
  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.name, server_path(server) %></td>
        <td><%= server.os %></td>
        <td><%= server.os_type %></td>
        <td><%= display_by_line(server.internal_ip_addresses.map(&:ip)) %></td>
        <td><%= display_by_line(server.external_ip_addresses.map(&:ip)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center-align">
  <%= paginate @servers %>
</div>

 <div class="fixed-action-btn horizontal">
    <%= link_to new_server_path, class: "btn-floating btn-large red" do %>
      <i class="large material-icons">add</i>
    <% end %>
 </div>

app/views/servers/new.html.erb
<%= render 'form' %>

app/views/servers/show.html.erb
<%= link_to edit_server_path(@server), class: "btn-floating btn-large waves-effect waves-light red right" do %>
  <i class="material-icons">mode_edit</i>
<% end %>
        
<h5 class="center-align">Server Details</h5>
<table class="bordered">
  <tbody>
    <tr>
      <th>Name</th>
      <td width="50%"><%= @server.name %></td>
    </tr>
    <tr>
      <th>CPU</th>
      <td><%= @server.cpu %></td>
    </tr>
    <tr>
      <th>Drive</th>
      <td><%= @server.drive %></td>
    </tr>
    <tr>
      <th>RAM</th>
      <td><%= @server.ram %></td>
    </tr>
    <tr>
      <th>OS</th>
      <td><%= @server.os %></td>
    </tr>
    <tr>
      <th>OS Type</th>
      <td><%= @server.os_type %></td>
    </tr>
    <tr>
      <th>Installed Applications</th>
      <td><%= simple_format(@server.applications) %></td>
    </tr>
  </tbody>
</table>

<div class="divider"></div>
<h5 class="center-align">IP Addresses</h5>

<table class="bordered">
  <thead>
    <tr>
      <th>IP</th>
      <th>Network Address</th>
      <th>Network Mask</th>
      <th>Gateway</th>
      <th>Address Type</th>
    </tr>
  </thead>
  <tbody>
    <% @server.ip_addresses.each do |ip_address| %>
      <tr>
        <td><%= ip_address.ip %></td>
        <td><%= ip_address.network_address %></td>
        <td><%= ip_address.network_mask %></td>
        <td><%= ip_address.gateway %></td>
        <td><%= ip_address.address_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="divider"></div>
<h5 class="center-align">Accounts</h5>

<table class="bordered">
  <thead>
    <tr>
      <th>Account Type</th>
      <th>User</th>
      <th>Password</th>
    </tr>
  </thead>
  <tbody>
    <% @server.accounts.each do |account| %>
      <tr>
        <td><%= account.account_type %></td>
        <td><%= account.user %></td>
        <td><%= account.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>